### PR TITLE
Eliminate Python dispatch from (de)serialization

### PR DESCRIPTION
**Pull request by slingamn**
This eliminates the performance regression from #197 by creating separate code paths for "native mode" and "user mode" serialization --- on the native path, the values are not boxed and the overhead of Python method dispatch is not incurred. The expected 3-microsecond saving seems to be achieved: https://gist.github.com/slingamn/c82b82084cf7720acf22

Here's where it gets a little weird / counterintuitive. The client detects whether to use "user mode" by testing, in the constructor, for the existence of attributes named `serialize` and `deserialize`. Therefore, the base class does not implement these methods --- they are instead exposed to Python under the names `_serialize` and `_deserialize`. This isn't ideal. It's also an API break, which makes it convenient that 1.6 hasn't been officially released yet.

Thoughts?

### CODE REVIEW

**Comment by slingamn** [comment]
Added some test coverage, fixed a small bug, and removed a macro I thought was counterintuitive.

**Comment by slingamn** [comment]
Any thoughts on the design? Thanks for your time.

**Comment by lericson** [comment]
I’ll get back to you ASAP!

**Comment by lericson** [comment]
So the C implementation is underscore prefixed, while the user land version is not? Isn't it easier, and more intuitive, to just test if the base class implementation has been replaced/overridden? I'm convinced there are ways of doing that -- or am I misunderstanding?

**Comment by slingamn** [comment]
You're totally right: there's a good way to detect overriding (basically testing `self.__class__.serialize is _pylibmc.client.serialize`). I had a mental block about this because of a [bad StackOverflow post](http://stackoverflow.com/questions/9436681/how-to-detect-method-overloading-in-subclasses-in-python); I think it's hard to detect overriding in a way that works for both new-style and old-style classes, but we don't have that problem.

This removes the API break, so I reverted the documentation changes. The expected speedup is still present.

**Comment by lericson** [comment]
You are a gentleman and a scholar.
