### ISSUE TITLE
pylibmc 1.2.1 build fails against libmemcached 0.52

### ISSUE THREAD

**Issue by chrislea** [lericson/pylibmc#57]
Here's the error:

```
running build_ext
building '_pylibmc' extension
creating build/temp.linux-x86_64-2.6
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -O2 -fPIC -DUSE_ZLIB -I/usr/include/python2.6 -c _pylibmcmodule.c -o build/temp.linux-x86_64-2.6/_pylibmcmodule.o
_pylibmcmodule.c: In function '_init_sasl':
_pylibmcmodule.c:2028: warning: implicit declaration of function 'sasl_client_init'
_pylibmcmodule.c:2029: error: 'SASL_NOMEM' undeclared (first use in this function)
_pylibmcmodule.c:2029: error: (Each undeclared identifier is reported only once
_pylibmcmodule.c:2029: error: for each function it appears in.)
_pylibmcmodule.c:2031: error: 'SASL_BADVERS' undeclared (first use in this function)
_pylibmcmodule.c:2033: error: 'SASL_BADPARAM' undeclared (first use in this function)
_pylibmcmodule.c:2035: error: 'SASL_NOMECH' undeclared (first use in this function)
_pylibmcmodule.c:2037: error: 'SASL_OK' undeclared (first use in this function)
_pylibmcmodule.c:2049: error: 'sasl_done' undeclared (first use in this function)
error: command 'gcc' failed with exit status 1
```

It does build against libmemcached 0.51, but 0.51 itself won't build on i386 machines, so right now 0.50 is the newest that can be used reliably across the usual architectures.
