### ISSUE TITLE
Compile error with libmemcached 1.0.12

### ISSUE THREAD

**Issue by MrTravisB** [lericson/pylibmc#104]
Here is the output of `pip install pylibmc`. This works fine with libmemcached 1.0.11

Downloading/unpacking pylibmc
  Downloading pylibmc-1.2.3.tar.gz (47kB): 47kB downloaded
  Running setup.py egg_info for package pylibmc

Installing collected packages: pylibmc
  Running setup.py install for pylibmc
    building '_pylibmc' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_ZLIB -I/opt/python2.7/include/python2.7 -c _pylibmcmodule.c -o build/temp.linux-x86_64-2.7/_pylibmcmodule.o -fno-strict-aliasing
    In file included from _pylibmcmodule.c:34:
    _pylibmcmodule.h:193:5: error: token "@" is not valid in preprocessor expressions
    _pylibmcmodule.c:1772:5: error: token "@" is not valid in preprocessor expressions
    _pylibmcmodule.c: In function ‘PylibMC_Client_get_stats’:
    _pylibmcmodule.c:1779: warning: implicit declaration of function ‘memcached_server_list’
    _pylibmcmodule.c:1779: warning: assignment makes pointer from integer without a cast
    _pylibmcmodule.c:1880:5: error: token "@" is not valid in preprocessor expressions
    error: command 'gcc' failed with exit status 1
    Complete output from command /opt/python2.7/bin/python -c "import setuptools;__file__='/tmp/pip-build/pylibmc/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-edqhXf-record/install-record.txt --single-version-externally-managed:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/pylibmc

copying pylibmc/**init**.py -> build/lib.linux-x86_64-2.7/pylibmc

copying pylibmc/client.py -> build/lib.linux-x86_64-2.7/pylibmc

copying pylibmc/pools.py -> build/lib.linux-x86_64-2.7/pylibmc

copying pylibmc/consts.py -> build/lib.linux-x86_64-2.7/pylibmc

copying pylibmc/test.py -> build/lib.linux-x86_64-2.7/pylibmc

copying pylibmc/**main**.py -> build/lib.linux-x86_64-2.7/pylibmc

running build_ext

building '_pylibmc' extension

creating build/temp.linux-x86_64-2.7

gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_ZLIB -I/opt/python2.7/include/python2.7 -c _pylibmcmodule.c -o build/temp.linux-x86_64-2.7/_pylibmcmodule.o -fno-strict-aliasing

In file included from _pylibmcmodule.c:34:

_pylibmcmodule.h:193:5: error: token "@" is not valid in preprocessor expressions

_pylibmcmodule.c:1772:5: error: token "@" is not valid in preprocessor expressions

_pylibmcmodule.c: In function ‘PylibMC_Client_get_stats’:

_pylibmcmodule.c:1779: warning: implicit declaration of function ‘memcached_server_list’

_pylibmcmodule.c:1779: warning: assignment makes pointer from integer without a cast

_pylibmcmodule.c:1880:5: error: token "@" is not valid in preprocessor expressions

error: command 'gcc' failed with exit status 1

---

Command /opt/python2.7/bin/python -c "import setuptools;**file**='/tmp/pip-build/pylibmc/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-edqhXf-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build/pylibmc
Storing complete log in /root/.pip/pip.log
